# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rl99gBJxpOq4owpUH22bYyP7Ny4CMvZt
"""

def run_CNN(data, labels):
  weights = [0, 2, 3, 4]
  print("CNN created")
  return weights

